#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ALIASES_FILE="$SCRIPT_DIR/.ddev_aliases"
BASHRC="$HOME/.bashrc"

if [ ! -f "$ALIASES_FILE" ]; then
    echo "❌ Không tìm thấy file .ddev_aliases"
    exit 1
fi

echo "🔧 Đang cài đặt DDEV aliases..."

if grep -q "\.ddev_aliases" "$BASHRC" 2>/dev/null; then
    echo "✅ Aliases đã được thêm vào ~/.bashrc trước đó"
else
    echo "" >> "$BASHRC"
    echo "# DDEV Aliases - Auto-generated by setup-aliases.sh" >> "$BASHRC"
    echo "if [ -f \"$ALIASES_FILE\" ]; then" >> "$BASHRC"
    echo "    source \"$ALIASES_FILE\"" >> "$BASHRC"
    echo "fi" >> "$BASHRC"
    echo "✅ Đã thêm aliases vào ~/.bashrc"
fi

source "$ALIASES_FILE"
echo "✅ Aliases đã được nạp!"

echo ""
echo "📝 Các alias đã sẵn sàng sử dụng:"
echo "   ds, dst, dr, ddes, dcom, dmage, ..."
echo ""
echo "💡 Chạy 'source ~/.bashrc' hoặc mở terminal mới để sử dụng."
