#!/bin/bash
## Description: Create admin or customer user
## Usage: create-user
## Example: "ddev create-user"

read -r -p "Create an admin (a) or a customer (c)? [a/c]: " account_type

if [[ "$account_type" == [Aa] ]]; then
  read -r -p "Username: " USERNAME
  read -r -p "Email: " EMAIL
  read -r -p "Password (at least 8 characters): " PASSWORD
  read -r -p "First Name: " FIRSTNAME
  read -r -p "Last Name: " LASTNAME
  
  ddev magento admin:user:create \
    --admin-user="${USERNAME}" \
    --admin-password="${PASSWORD}" \
    --admin-email="${EMAIL}" \
    --admin-firstname="${FIRSTNAME}" \
    --admin-lastname="${LASTNAME}"
elif [[ "$account_type" == [Cc] ]]; then
  read -r -p "Email: " EMAIL
  read -r -p "Password (at least 8 characters): " PASSWORD
  read -r -p "First Name: " FIRSTNAME
  read -r -p "Last Name: " LASTNAME
  
  ddev exec bash -c "
    if [ ! -f bin/n98-magerun2.phar ]; then
      echo 'Downloading n98-magerun2.phar...'
      curl -sS -O https://files.magerun.net/n98-magerun2.phar
      curl -sS -o n98-magerun2.phar.sha256 https://files.magerun.net/sha256.php?file=n98-magerun2.phar
      shasum -a 256 -c n98-magerun2.phar.sha256 || (echo 'sha256 checksum do not match!' && exit 1)
      chmod +x n98-magerun2.phar
      mkdir -p bin
      mv n98-magerun2.phar bin
    fi
    php bin/n98-magerun2.phar customer:create '${EMAIL}' '${PASSWORD}' '${FIRSTNAME}' '${LASTNAME}'
  "
else
  echo "Invalid option. Please choose either a or c."
  exit 1
fi
