#!/usr/bin/env bash
#ddev-generated

## Description: Run Grunt tasks
## Usage: grunt [task]
## Example: "ddev grunt" or "ddev grunt watch"

ddev exec bash -c "
  if ! command -v grunt &> /dev/null; then
    echo 'Grunt not found. Installing...'
    npm install -g grunt-cli
  fi
  grunt $*
"
