#!/bin/bash
## Description: Compile Magento DI and generate code
## Usage: compile
## Example: "ddev compile"

echo "Cleaning generated code..."
rm -rf generated/code var/view_preprocessed

echo "Compiling DI..."
bin/magento setup:di:compile

echo "Compilation completed!"
