#!/bin/bash
## Description: Run Grunt tasks
## Usage: grunt [task]
## Example: "ddev grunt" or "ddev grunt watch"

if ! command -v grunt &> /dev/null; then
  echo "Grunt not found. Installing..."
  npm install -g grunt-cli
fi

grunt "$@"
