#!/bin/bash
## Description: Tail Magento log files
## Usage: log [log_files]
## Example: "ddev log" or "ddev log system.log exception.log"

CONTAINER_LOG_PATH="var/log/"

if [ -z "$1" ]; then
  find "$CONTAINER_LOG_PATH" -type f -name "*.log" -exec tail -f {} + 2>/dev/null || echo "No log files found"
else
  for log_file in "$@"; do
    if [ -f "$CONTAINER_LOG_PATH$log_file" ]; then
      echo "=== $log_file ==="
      tail -f "$CONTAINER_LOG_PATH$log_file" &
    else
      echo "Log file $log_file not found"
    fi
  done
  wait
fi
