#!/bin/bash
## Description: Run n98-magerun2 commands
## Usage: n98 [command]
## Example: "ddev n98 sys:info" or "ddev n98 customer:list"

if [ ! -f bin/n98-magerun2.phar ]; then
  echo "Downloading n98-magerun2.phar, just a moment..."
  curl -sS -O https://files.magerun.net/n98-magerun2.phar
  curl -sS -o n98-magerun2.phar.sha256 https://files.magerun.net/sha256.php?file=n98-magerun2.phar
  shasum -a 256 -c n98-magerun2.phar.sha256 || (echo "sha256 checksum do not match!" && exit 1)
  chmod +x n98-magerun2.phar
  mkdir -p bin
  mv n98-magerun2.phar bin
fi

bin/n98-magerun2.phar "$@"
